### ISSUE TITLE
Waiting for code...

### ISSUE THREAD

**Issue by cht619** [Thinklab-SJTU/GAMF#1]

**Comment by Tam-JQK** [comment]
Waiting for code...

**Comment by P0werWeirdo** [comment]
Waiting for code...

**Comment by rogerwwww** [comment]
Dear all, thanks for your interest in our paper and thanks for your patience. We finished reorganizing the code before the end of 2022 and published it on GitHub.

And we are sorry that we mistakenly place the code in the 'dev' branch that did not display on Github's webpage by default. Now we have fixed this issue and please see the code at https://github.com/Thinklab-SJTU/GAMF/tree/dev
