### ISSUE TITLE
FL CIFAR-100 setup

### ISSUE THREAD

**Issue by honggudrnjs** [Thinklab-SJTU/GAMF#4]
Hi, thx for sharing the amazing work.
However,  the performance was not good when I run the FL code on CIFAR-100.
Optimizer was Adam, lr 0.0005, weight decay 0.001 was used.
The setup is different what is used for reproduce of CIFAR-100 results?

**Comment by only-changer** [comment]
I have sent your the config via email, sorry for the inconvenience.
